package constant

const (
	C1337xBaseURL            = "https://www.1337x.to"
	FreeGOGListURL           = "https://freegogpcgames.com/a-z-games-list"
	GOGSearchURL             = "https://embed.gog.com/games/ajax/filtered"
	GOGDetailsURL            = "https://api.gog.com/products"
	SteamSearchURL           = "https://store.steampowered.com/search"
	SteamAppDetailURL        = "https://store.steampowered.com/api/appdetails"
	SteamAllAppsURL          = "https://api.steampowered.com/ISteamApps/GetAppList/v2/?format=json"
	HowLongToBeatURL         = "https://howlongtobeat.com"
	HowLongToBeatSearchURL   = "https://howlongtobeat.com/api/search"
	HowLongToBeatDetailsURL  = "https://howlongtobeat.com/game"
	XatabBaseURL             = "https://byxatab.com"
	GoogleSearchURL          = "https://www.google.com/search"
	BingSearchURL            = "https://www.bing.com/search"
	OnlineFixURL             = "https://online-fix.me"
	OnlineFixCSRFURL         = "https://online-fix.me/engine/ajax/authtoken.php"
	IGDBGameURL              = "https://api.igdb.com/v4/games"
	IGDBLanguagesURL         = "https://api.igdb.com/v4/languages"
	IGDBAlternativeNamesURL  = "https://api.igdb.com/v4/alternative_names"
	IGDBLanguageSupportsURL  = "https://api.igdb.com/v4/language_supports"
	IGDBScreenshotsURL       = "https://api.igdb.com/v4/screenshots"
	IGDBInvolvedCompaniesURL = "https://api.igdb.com/v4/involved_companies"
	IGDBCompaniesURL         = "https://api.igdb.com/v4/companies"
	IGDBCoversURL            = "https://api.igdb.com/v4/covers"
	TwitchAuthURL            = "https://id.twitch.tv/oauth2/token"
	Steam250Top250URL        = "https://steam250.com/top250"
	Steam250BestOfTheYearURL = "https://steam250.com/%v"
	Steam250WeekTop50URL     = "https://steam250.com/7day"
	Steam250MostPlayedURL    = "https://steam250.com/most_played"
	// SteamPackageDetailURL   = "https://store.steampowered.com/api/packagedetails"
	// SteamSearchSuggestURL   = "https://store.steampowered.com/search/suggest"
)
